### ISSUE TITLE
Update the packages used in this project

### ISSUE THREAD

**Issue by AWash227** [AWash227/reddit-but-its-tiktok#10]
Some of the packages/dependencies being used in this project are out of date. Give them an upgrade and crush some potential security problems.

**Comment by s1l1c0np1r4t3** [comment]
I would like to be assigned this please and get it done.

**Comment by AWash227** [comment]
Have fun! You've been assigned.

**Comment by s1l1c0np1r4t3** [comment]
Please close issue. Thanks!
