### ISSUE TITLE
Minor typo in README.md

### ISSUE THREAD

**Issue by jlong5795** [AWash227/reddit-but-its-tiktok#12]
Typo in port number in step 5 of "How to Run".

**Comment by s1l1c0np1r4t3** [comment]
I will go ahead an get this done for you as well while I work on the other issue.

**Comment by mrinal-27** [comment]
Hey @jlong5795 can I fix this?

**Comment by jlong5795** [comment]
@mrinal-27 I opened this issue but am not the owner of the project. But it appears that @s1l1c0np1r4t3 is working on this as part of another PR they will submit.

**Comment by jlong5795** [comment]
Closing issue and incorporating with issue #10
