### ISSUE TITLE
When fetching new posts, it will reload some of the same posts

### ISSUE THREAD

**Issue by AWash227** [AWash227/reddit-but-its-tiktok#7]
This is most likely an issue with either fetching data from the api (look at the "after" part of the request), or it has to do with the pagination I implemented.

**Comment by tavvfiq** [comment]
can i be assigned with this bug? it seems that i have been encounter it in my other project before. thanks!!

**Comment by AWash227** [comment]
You've been assigned, good luck!

**Comment by tavvfiq** [comment]
thank you so much
