### ISSUE TITLE
The reddit comments don't fetch the correct user

### ISSUE THREAD

**Issue by AWash227** [AWash227/reddit-but-its-tiktok#8]
Look at the Reddit API and figure out how to query the correct user for each comment. Shouldn't be too hard. You'll learn how to work with API's, data fetching, and React Lifecycle / hooks.

**Comment by wcorderolara** [comment]
could you please assign this to me? :)

**Comment by dannyflatiron** [comment]
I have it done, could you assign it to me?

**Comment by AWash227** [comment]
Thanks for the interest, @dannyflatiron finished it though, so I merged his pull request hope you find another issue to work on @wcorderolara :)
